[package]
name = "rsutil"
version = "0.0.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rsutil"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
sysinfo = "0.37.2"
once_cell = "1.21.3"
